---

- name: Install System Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - postgresql-client
    - postgresql-contrib
    - postgresql-9.3-postgis-2.1
    - postgresql-9.3-postgis-scripts    
    - libpq-dev
    - python-pip
    - python-psycopg2
    - git
    - libmemcached-dev
    - binutils
    - libproj-dev
    - gdal-bin
    - cgi-mapserver

- name: Clone Django Repository
  git: repo=https://github.com/tpeek/django-imager.git dest={{ home }} force=yes

- name: Install Python Dependencies
  sudo: yes
  pip:
    state: present
    requirements: "{{ home }}/requirements.txt"

- name: Get DB Password
  include_vars: secrets.yml

- name: Set DB URL
  set_fact: 
    db_url: "{{ db_host.ec2_engine }}://{{ db_host.ec2_master_username }}:{{ db_password }}@{{ db_host.ec2__address }}:{{ db_host.ec2__port }}/{{ db_host.ec2_DBName }}"

- name: Run Migrations
  environment:
    DATABASE_URL: "{{ db_url }}"
    SECRET_KEY: "{{ secret_key }}"
    DEBUG: False
    EMAIL_HOST_USER: "{{ email_user }}"
    EMAIL_HOST_PASSWORD: "{{ email_pass }}"
    ALLOWED_HOSTS: "{{ allowed_hosts }}"
  django_manage:
    app_path: "{{ django_home }}"
    settings: imagersite.production
    command: migrate

- name: Collect Static Files
  environment:
    DATABASE_URL: "{{ db_url }}"
    SECRET_KEY: "{{ secret_key }}"
    DEBUG: False
    EMAIL_HOST_USER: "{{ email_user }}"
    EMAIL_HOST_PASSWORD: "{{ email_pass }}"
    ALLOWED_HOSTS: "{{ allowed_hosts }}"
  django_manage:
    app_path: '{{ django_home }}'
    settings: imagersite.production
    command: collectstatic
